apiVersion: apps/v1
kind: Deployment

metadata: 
  name: coffee-shop
  namespace: mamu
spec: 
  replicas: 2

  selector:
    matchLabels: 
     app: coffee-shop
      
  template: 
    metadata:
      labels:
       app: coffee-shop

    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
           - containerPort: 80 
          env:
            - name: COURSE
              value: "DevSecOps with aws"

            - name: TRAINER
              value: "sivakumar reddy"

            - name: DURATION
              value: "120Hrs"  


