apiVersion: apps/v1
kind: Deployment

metadata:
  name: secret-data

spec:
  replicas: 3

  selector:
    matchLabels:
      app: secret-data

  template:
    metadata:
      labels:
        app: secret-data

    spec:
      containers:
        - name: nginx
          image: nginx:1.27

          ports:
            - containerPort: 80

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-data
                  key: DB_PASSWORD

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "200m"
              memory: "256Mi"